apiVersion: dapr.io/v1alpha1
kind: Configuration

metadata:
  name: dapr-config-docker

spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "otel-collector.docker.local:50051"
      isSecure: true
      protocol: grpc
  logging:
    apiLogging:
      enabled: true
      obfuscateURLs: false
  metrics:
    enabled: true
    rules: []
    http:
      increasedCardinality: true
    latencyDistributionBuckets: [1, 2, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
  metric:
    enabled: true
    exporters:
      otel:
        enabled: true
        endpointAddress: "otel-collector.docker.local:50051"
        isSecure: true
        protocol: grpc