apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets-kafka-tls
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: .dapr/certs/cert-store.json
  - name: multiValued
    value: "true"
